/* Generated by Together */

#ifndef LAMPE_H
#define LAMPE_H

/**
 * @interface 
 */
class Lamp {
public:

    virtual void off() =0;

    virtual void on() =0;

    virtual bool isOn() =0;

    virtual ~Lamp() = 0;
};
inline
Lamp::~Lamp(){}
#endif //LAMPE_H
